version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gem-cache-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache
      - run:
          name: Install ruby dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION }}
            - npm-cache-{{ .Environment.CACHE_VERSION }}-
      - run:
          name: Install node dependencies
          command: npm install --ignore-scripts --verbose
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}-{{ .Environment.CACHE_VERSION }}
          paths:
            - node_modules
      - run:
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run:
          name: Build site files
          command: npm run build
      - run:
          name: Install scss_lint
          command: gem install scss_lint
      - run:
          name: Run test
          command: npm test
      - run:
          name: Checking build
          command: ls -agolf _site/
